id: A49B59991
base_file: fEE40.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:29:10.866190
  last_modified_at: 2022-05-31 05:29:10.866197
